dataset_class: AudioDataset
dataset:
  both:
    formats: ['*/']
    sr: 16000

  train:
    paths: ['/home/angusturner/datasets/vctk_16k/train']
    patch_size: 16000
  test:
    paths: ['/home/angusturner/datasets/vctk_16k/test']
    patch_size: 16000