dataset_class: AudioDataset
dataset:
  both:
    formats: ['*/']
    sr: 16000

  train:
#    paths: ['/home/angusturner/data/datasets/vctk_16k/train']
    # paths: ['/home/ubuntu/data_disk/known_speakers/']
    paths: ['/home/angusturner/storage/known_speakers/train']
    patch_size: 16000

  test:
    # paths: ['/home/ubuntu/data_disk/vctk_16k/test']
#    paths: ['/home/angusturner/data/datasets/vctk_16k/test']
    paths: ['/home/angusturner/storage/known_speakers/test']
    patch_size: 16000
